name: smart_home_app
description: Приложение для управления устройствами умного дома.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  wifi_iot: ^0.3.19+2
  network_info_plus: ^4.1.0
  connectivity_plus: ^5.0.2
  permission_handler: ^11.1.0
  app_settings: ^5.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
